services:
  db:
    image: mysql:8.4
    container_name: riego-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: riego
      MYSQL_USER: riego
      MYSQL_PASSWORD: riego123
    ports:
      - "3307:3306"
    volumes:
      - riego_data:/var/lib/mysql
      - ./riego.sql:/docker-entrypoint-initdb.d/riego.sql:ro

volumes:
  riego_data:
